Fix QEMU build for glibc-2.17
The clock_* functions are no longer in librt starting with glibc-2.17,
but timer_* functions are.

This solves linker errors similar to this:
(32-bit archlinux installation with glibc 2.17-3, binutils 2.23.1-3, glib2 2.34.3-1)

/usr/bin/ld: ../qemu-timer.o: undefined reference to symbol 'timer_settime@@GLIBC_2.2'
/usr/bin/ld: note: 'timer_settime@@GLIBC_2.2' is defined in DSO /usr/lib/librt.so.1 so try adding it to the linker command line
/usr/lib/librt.so.1: could not read symbols: Invalid operation

Change-Id: I2d335d065457788ef8aada7d0d500e84ba31e4d0
Signed-off-by: Kyösti Mälkki <kyosti.malkki@gmail.com>
Reviewed-on: http://review.coreboot.org/2504
Tested-by: build bot (Jenkins)
Reviewed-by: Stefan Reinauer <stefan.reinauer@coreboot.org>